version: '3.8'

services:
  birthday-bot:
    build: .
    container_name: birthday_bot
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_NAME=/data/birthdays.db
      - TZ=America/Argentina/Buenos_Aires # Adjust timezone as needed
    volumes:
      - ./data:/data
